DROP TRIGGER IF EXISTS products_variant_parent_guard_update;
DROP TRIGGER IF EXISTS products_variant_parent_guard_insert;
DROP INDEX IF EXISTS idx_product_uoms_lookup;
DROP INDEX IF EXISTS uq_product_uoms_base;
DROP TABLE IF EXISTS product_uoms;
DROP INDEX IF EXISTS idx_products_parent;
ALTER TABLE daily_product_rollups DROP COLUMN qty_microunits;
ALTER TABLE supplier_invoice_lines DROP COLUMN invoiced_qty_microunits;
ALTER TABLE supplier_invoices DROP COLUMN matched_qty_microunits;
ALTER TABLE sale_return_items DROP COLUMN qty_microunits;
ALTER TABLE purchase_order_items DROP COLUMN quantity_received_microunits;
ALTER TABLE purchase_order_items DROP COLUMN quantity_ordered_microunits;
ALTER TABLE purchase_receipt_lines DROP COLUMN quantity_microunits;
ALTER TABLE order_items DROP COLUMN quantity_microunits;
ALTER TABLE stock_losses DROP COLUMN quantity_microunits;
ALTER TABLE inventory_count_lines DROP COLUMN difference_qty_microunits;
ALTER TABLE inventory_count_lines DROP COLUMN system_qty_microunits;
ALTER TABLE inventory_count_lines DROP COLUMN counted_qty_microunits;
ALTER TABLE branch_stock_policies DROP COLUMN reorder_qty_microunits;
ALTER TABLE branch_stock_policies DROP COLUMN reorder_point_microunits;
ALTER TABLE branch_stock_policies DROP COLUMN min_stock_microunits;
ALTER TABLE inventory_movements DROP COLUMN stock_after_microunits;
ALTER TABLE inventory_movements DROP COLUMN quantity_delta_microunits;
ALTER TABLE branch_product_stock DROP COLUMN stock_microunits;
ALTER TABLE inventory_batches DROP COLUMN stock_microunits;
ALTER TABLE product_recipes DROP COLUMN quantity_microunits;
ALTER TABLE sale_items DROP COLUMN base_quantity_microunits;
ALTER TABLE sale_items DROP COLUMN factor_denominator;
ALTER TABLE sale_items DROP COLUMN factor_numerator;
ALTER TABLE sale_items DROP COLUMN entered_quantity_microunits;
ALTER TABLE sale_items DROP COLUMN sold_uom_code;
ALTER TABLE sale_items DROP COLUMN sold_uom_id;
ALTER TABLE products DROP COLUMN stock_microunits;
ALTER TABLE products DROP COLUMN is_sellable;
ALTER TABLE products DROP COLUMN variant_price_override_cents;
ALTER TABLE products DROP COLUMN parent_product_id;
DELETE FROM schema_meta WHERE key = 'catalog.variants_uom.sprint31';
