INSERT /* CUSTOMER_ORDER_DOWN_PROTECTED: RAISE(ABORT via atomic_guards CHECK) */ INTO atomic_guards(id, ok) SELECT 'orders.customer_orders.sprint43.down', CASE WHEN EXISTS (SELECT 1 FROM customer_order_notifications) OR EXISTS (SELECT 1 FROM customer_order_fulfillments) OR EXISTS (SELECT 1 FROM customer_order_items) OR EXISTS (SELECT 1 FROM customer_orders) THEN 0 ELSE 1 END;
DROP TRIGGER IF EXISTS backup_epoch_customer_order_notifications_delete;
DROP TRIGGER IF EXISTS backup_epoch_customer_order_notifications_update;
DROP TRIGGER IF EXISTS backup_epoch_customer_order_notifications_insert;
DROP TRIGGER IF EXISTS backup_epoch_customer_order_fulfillments_delete;
DROP TRIGGER IF EXISTS backup_epoch_customer_order_fulfillments_update;
DROP TRIGGER IF EXISTS backup_epoch_customer_order_fulfillments_insert;
DROP TRIGGER IF EXISTS backup_epoch_customer_order_items_delete;
DROP TRIGGER IF EXISTS backup_epoch_customer_order_items_update;
DROP TRIGGER IF EXISTS backup_epoch_customer_order_items_insert;
DROP TRIGGER IF EXISTS backup_epoch_customer_orders_delete;
DROP TRIGGER IF EXISTS backup_epoch_customer_orders_update;
DROP TRIGGER IF EXISTS backup_epoch_customer_orders_insert;
DROP TRIGGER IF EXISTS customer_order_fulfillments_scope_immutable;
DROP TRIGGER IF EXISTS customer_order_fulfillments_quantity_guard_update;
DROP TRIGGER IF EXISTS customer_order_fulfillments_quantity_guard;
DROP TRIGGER IF EXISTS customer_orders_fulfilled_items_guard;
DROP TRIGGER IF EXISTS customer_orders_expiry_notice_guard;
DROP TRIGGER IF EXISTS customer_orders_status_transition_guard;
DROP INDEX IF EXISTS idx_customer_order_notifications_retry;
DROP INDEX IF EXISTS idx_customer_order_fulfillments_lease;
DROP INDEX IF EXISTS idx_customer_order_fulfillments_order;
DROP INDEX IF EXISTS idx_customer_order_items_allocation;
DROP INDEX IF EXISTS idx_customer_order_items_order;
DROP INDEX IF EXISTS idx_customer_orders_expiry;
DROP INDEX IF EXISTS idx_customer_orders_pickup;
DROP INDEX IF EXISTS idx_authorization_tokens_customer_order_reprice;
DROP TABLE customer_order_notifications;
DROP TABLE customer_order_fulfillments;
DROP TABLE customer_order_items;
DROP TABLE customer_orders;
ALTER TABLE authorization_tokens DROP COLUMN terminal_session_id;
ALTER TABLE authorization_tokens DROP COLUMN customer_order_id;
DROP INDEX IF EXISTS uq_sale_items_tenant_sale_id;
DROP INDEX IF EXISTS uq_product_uoms_tenant_id;
DELETE FROM schema_meta WHERE key = 'orders.customer_orders.sprint43';
DELETE FROM atomic_guards WHERE id = 'orders.customer_orders.sprint43.down';
