INSERT /* RECURRING_SALES_DOWN_PROTECTED: RAISE(ABORT via atomic_guards CHECK) */ INTO atomic_guards(id, ok) SELECT 'sales.recurring.sprint44.down', CASE WHEN EXISTS (SELECT 1 FROM recurring_proration_adjustments) OR EXISTS (SELECT 1 FROM recurring_occurrence_items) OR EXISTS (SELECT 1 FROM recurring_occurrences) OR EXISTS (SELECT 1 FROM recurring_plan_items) OR EXISTS (SELECT 1 FROM recurring_plans) OR EXISTS (SELECT 1 FROM authorization_tokens WHERE recurring_idempotency_key_hash IS NOT NULL OR recurring_run_result_json IS NOT NULL) THEN 0 ELSE 1 END;
DROP TRIGGER IF EXISTS epoch_recurring_proration_adjustments_delete;
DROP TRIGGER IF EXISTS epoch_recurring_proration_adjustments_update;
DROP TRIGGER IF EXISTS epoch_recurring_proration_adjustments_insert;
DROP TRIGGER IF EXISTS epoch_recurring_occurrence_items_delete;
DROP TRIGGER IF EXISTS epoch_recurring_occurrence_items_update;
DROP TRIGGER IF EXISTS epoch_recurring_occurrence_items_insert;
DROP TRIGGER IF EXISTS epoch_recurring_occurrences_delete;
DROP TRIGGER IF EXISTS epoch_recurring_occurrences_update;
DROP TRIGGER IF EXISTS epoch_recurring_occurrences_insert;
DROP TRIGGER IF EXISTS epoch_recurring_plan_items_delete;
DROP TRIGGER IF EXISTS epoch_recurring_plan_items_update;
DROP TRIGGER IF EXISTS epoch_recurring_plan_items_insert;
DROP TRIGGER IF EXISTS epoch_recurring_plans_delete;
DROP TRIGGER IF EXISTS epoch_recurring_plans_update;
DROP TRIGGER IF EXISTS epoch_recurring_plans_insert;
DROP TRIGGER IF EXISTS recurring_proration_adjustments_no_delete;
DROP TRIGGER IF EXISTS recurring_proration_adjustments_immutable;
DROP TRIGGER IF EXISTS recurring_occurrence_items_no_delete;
DROP TRIGGER IF EXISTS recurring_occurrence_items_immutable;
DROP TRIGGER IF EXISTS recurring_occurrences_snapshot_immutable;
DROP TRIGGER IF EXISTS recurring_plan_items_no_delete;
DROP TRIGGER IF EXISTS recurring_plan_items_immutable;
DROP TRIGGER IF EXISTS recurring_plans_version_immutable;
DROP INDEX IF EXISTS idx_recurring_proration_original;
DROP INDEX IF EXISTS idx_recurring_occurrences_plan_period;
DROP INDEX IF EXISTS idx_recurring_plan_items_plan;
DROP INDEX IF EXISTS idx_recurring_plans_customer;
DROP INDEX IF EXISTS idx_recurring_plans_lease;
DROP INDEX IF EXISTS idx_recurring_plans_due;
DROP TABLE recurring_proration_adjustments;
DROP TABLE recurring_occurrence_items;
DROP TABLE recurring_occurrences;
DROP TABLE recurring_plan_items;
DROP TABLE recurring_plans;
DROP INDEX IF EXISTS idx_authorization_tokens_recurring_manual;
ALTER TABLE authorization_tokens DROP COLUMN recurring_run_result_json;
ALTER TABLE authorization_tokens DROP COLUMN recurring_idempotency_key_hash;
DROP INDEX IF EXISTS uq_accounts_receivable_tenant_id;
DELETE FROM schema_meta WHERE key = 'sales.recurring.sprint44';
DELETE FROM atomic_guards WHERE id = 'sales.recurring.sprint44.down';
