INSERT /* MOBILE_PUSH_DOWN_PROTECTED: require READY KPBK1 backup, compatible registry, and exact tenant epoch */ INTO atomic_guards(id, ok) SELECT 'mobile.push.sprint45.down', CASE WHEN EXISTS (SELECT tenant_id FROM push_privacy_settings UNION SELECT tenant_id FROM push_consents UNION SELECT tenant_id FROM push_subscriptions UNION SELECT tenant_id FROM push_events UNION SELECT tenant_id FROM push_deliveries) AND EXISTS (SELECT affected.tenant_id FROM (SELECT tenant_id FROM push_privacy_settings UNION SELECT tenant_id FROM push_consents UNION SELECT tenant_id FROM push_subscriptions UNION SELECT tenant_id FROM push_events UNION SELECT tenant_id FROM push_deliveries) affected JOIN tenant_data_epochs epoch ON epoch.tenant_id = affected.tenant_id WHERE NOT EXISTS (SELECT 1 FROM data_backups backup WHERE backup.tenant_id = affected.tenant_id AND backup.format_version = 'KPBK1' AND backup.registry_version = 'registry-1' AND backup.snapshot_epoch = epoch.epoch AND backup.status = 'READY' AND backup.global_hash IS NOT NULL AND backup.ready_at IS NOT NULL)) THEN 0 ELSE 1 END;
DROP TRIGGER IF EXISTS epoch_push_deliveries_delete;
DROP TRIGGER IF EXISTS epoch_push_deliveries_update;
DROP TRIGGER IF EXISTS epoch_push_deliveries_insert;
DROP TRIGGER IF EXISTS epoch_push_events_delete;
DROP TRIGGER IF EXISTS epoch_push_events_update;
DROP TRIGGER IF EXISTS epoch_push_events_insert;
DROP TRIGGER IF EXISTS epoch_push_subscriptions_delete;
DROP TRIGGER IF EXISTS epoch_push_subscriptions_update;
DROP TRIGGER IF EXISTS epoch_push_subscriptions_insert;
DROP TRIGGER IF EXISTS epoch_push_consents_delete;
DROP TRIGGER IF EXISTS epoch_push_consents_update;
DROP TRIGGER IF EXISTS epoch_push_consents_insert;
DROP TRIGGER IF EXISTS epoch_push_privacy_settings_delete;
DROP TRIGGER IF EXISTS epoch_push_privacy_settings_update;
DROP TRIGGER IF EXISTS epoch_push_privacy_settings_insert;
DROP INDEX IF EXISTS idx_push_deliveries_slo;
DROP INDEX IF EXISTS idx_push_deliveries_due;
DROP INDEX IF EXISTS idx_push_events_due;
DROP INDEX IF EXISTS idx_push_subscriptions_dispatch;
DROP INDEX IF EXISTS idx_push_consents_user_purpose;
DROP TABLE push_deliveries;
DROP TABLE push_events;
DROP TABLE push_subscriptions;
DROP TABLE push_consents;
DROP TABLE push_privacy_settings;
DELETE FROM schema_meta WHERE key = 'mobile.push.sprint45';
DELETE FROM atomic_guards WHERE id = 'mobile.push.sprint45.down';
