import { describe, expect, it, vi } from 'vitest';

describe('features flags default off', () => {
  it('checkout/print/vitrina/owner off sin env', async () => {
    vi.resetModules();
    vi.stubEnv('PUBLIC_FEATURE_POS_CHECKOUT', '');
    vi.stubEnv('PUBLIC_FEATURE_PRINT_TEMPLATES', '');
    vi.stubEnv('PUBLIC_FEATURE_VITRINA', '');
    vi.stubEnv('PUBLIC_FEATURE_OWNER_MODE', '');
    vi.stubEnv('PUBLIC_FEATURE_' + 'OWNER_PUSH', '');
    vi.stubEnv('PUBLIC_FEATURE_LEDGER_AR_AP', '');
    vi.stubEnv('PUBLIC_FEATURE_REPORTING_CATALOG', '');
    vi.stubEnv('PUBLIC_FEATURE_REPORTING_EXPORT', '');
    vi.stubEnv('PUBLIC_FEATURE_ORDERS_KDS', '');
    vi.stubEnv('PUBLIC_FEATURE_STOCK_TRANSFERS', '');
    vi.stubEnv('PUBLIC_FEATURE_PURCHASING_PARTIAL_RECEIVE', '');
    vi.stubEnv('PUBLIC_FEATURE_' + 'PURCHASING_THREE_WAY', '');
    vi.stubEnv('PUBLIC_FEATURE_' + 'PAYMENTS_QR_WALLETS', '');
    vi.stubEnv('PUBLIC_FEATURE_' + 'PAYMENTS_CARD_ACQUIRER', '');
    vi.stubEnv('PUBLIC_FEATURE_' + 'MESSAGING_WHATSAPP', '');
    vi.stubEnv('PUBLIC_FEATURE_' + 'LOYALTY_POINTS', '');
    vi.stubEnv('PUBLIC_FEATURE_' + 'CLIENT_OFFLOADING', '');
    vi.stubEnv('PUBLIC_FEATURE_' + 'HARDWARE_PRINT_FALLBACK', '');
    vi.stubEnv('PUBLIC_FEATURE_' + 'FISCAL_CIRCUIT_BREAKER', '');
    vi.stubEnv('PUBLIC_FEATURE_' + 'FISCAL_TRANSPORT_PLUGINS', '');
    vi.stubEnv('PUBLIC_FEATURE_' + 'SALES_RETURNS', '');
    vi.stubEnv('PUBLIC_FEATURE_' + 'PRICING_PROMOTIONS', '');
    vi.stubEnv('PUBLIC_FEATURE_' + 'CATALOG_VARIANTS', '');
    vi.stubEnv('PUBLIC_FEATURE_' + 'CATALOG_UOM', '');
    vi.stubEnv('PUBLIC_FEATURE_' + 'SALES_LAYAWAY', '');
    vi.stubEnv('PUBLIC_FEATURE_' + 'LEDGER_CHART_OF_ACCOUNTS', '');
    vi.stubEnv('PUBLIC_FEATURE_' + 'SALES_QUOTES', '');
    vi.stubEnv('PUBLIC_FEATURE_' + 'PURCHASING_RETURNS', '');
    vi.stubEnv('PUBLIC_FEATURE_' + 'LEDGER_STORE_CREDIT', '');
    vi.stubEnv('PUBLIC_FEATURE_' + 'SALES_INSTALLMENTS', '');
    vi.stubEnv('PUBLIC_FEATURE_' + 'SALES_COMMISSIONS', '');
    vi.stubEnv('PUBLIC_FEATURE_' + 'INVENTORY_LOCATIONS', '');

    const mod = await import('./features.js');
    expect(mod.isPosCheckoutEnabled()).toBe(false);
    expect(mod.isPrintTemplatesEnabled()).toBe(false);
    expect(mod.isVitrinaEnabled()).toBe(false);
    expect(mod.isOwnerModeEnabled()).toBe(false);
    expect(mod.isOwnerPushEnabled()).toBe(false);
    expect(mod.isLedgerArApEnabled()).toBe(false);
    expect(mod.isReportingCatalogEnabled()).toBe(false);
    expect(mod.isReportingExportEnabled()).toBe(false);
    expect(mod.isOrdersKdsEnabled()).toBe(false);
    expect(mod.isStockTransfersEnabled()).toBe(false);
    expect(mod.isPartialReceiveEnabled()).toBe(false);
    expect(mod.isPurchasingThreeWayEnabled()).toBe(false);
    expect(mod.isPaymentsQrWalletsEnabled()).toBe(false);
    expect(mod.isPaymentsCardAcquirerEnabled()).toBe(false);
    expect(mod.isMessagingWhatsAppEnabled()).toBe(false);
    expect(mod.isLoyaltyPointsEnabled()).toBe(false);
    expect(mod.isClientOffloadingEnabled()).toBe(false);
    expect(mod.isHardwarePrintFallbackEnabled()).toBe(false);
    expect(mod.isFiscalCircuitBreakerEnabled()).toBe(false);
    expect(mod.isFiscalTransportPluginsEnabled()).toBe(false);
    expect(mod.isSalesReturnsEnabled()).toBe(false);
    expect(mod.isPricingPromotionsEnabled()).toBe(false);
    expect(mod.isCatalogVariantsEnabled()).toBe(false);
    expect(mod.isCatalogUomEnabled()).toBe(false);
    expect(mod.isSalesLayawayEnabled()).toBe(false);
    expect(mod.isLedgerChartOfAccountsEnabled()).toBe(false);
    expect(mod.isSalesQuotesEnabled()).toBe(false);
    expect(mod.isPurchasingReturnsEnabled()).toBe(false);
    expect(mod.isLedgerStoreCreditEnabled()).toBe(false);
    expect(mod.isSalesInstallmentsEnabled()).toBe(false);
    expect(mod.isSalesCommissionsEnabled()).toBe(false);
    expect(mod.isInventoryLocationsEnabled()).toBe(false);
    vi.unstubAllEnvs();
  });
});
